db:
  image: mysql:5.5
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=dbpass
    - MYSQL_DATABASE=wordpress
    - MYSQL_HOME=/etc
  volumes:
    - .docker/etc/my.cnf:/etc/my.cnf
    - ./data/logs:/var/log/app
  hostname: dbhost
  expose:
    - "3306"
  dns:
    - 8.8.8.8
    - 8.8.4.4
web:
  build: .
  command: /start.sh
  environment:
    - COMPOSER_HOME=/.composer
    - WP_CLI_CONFIG_PATH=/var/www/wp-cli.yml
  expose:
    - "80"
  ports: 
   - "80:80"
  volumes:
    - ./data/wordpress-core:/var/www/wordpress-core
    - ./data/wordpress-plugins:/var/www/wordpress-content/plugins
    - ./data/wordpress-themes:/var/www/wordpress-content/themes
    - ./data/wordpress-uploads:/var/www/wordpress-content/uploads
    - ./data/logs:/var/log/app
  links:
    - db:dbhost
  hostname: wordpress
  dns:
    - 8.8.8.8
    - 8.8.4.4